# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres:12.19
    restart: always
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: test
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  backend:
      image: 'docker-spring-boot-postgres:latest'
      build:
        context: .
      depends_on:
        - db
      ports:
        - 8080:8080
